# This file is a template, and might need editing before it works on your project.
default:
  image: node:latest

  # Validate that the repository contains a package.json and extract a few values from it.
  before_script:
    - |
      if [[ ! -f package.json ]]; then
        echo "No package.json found! A package.json file is required to publish a package to GitLab's NPM registry."
        echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#creating-a-project'
        exit 1
      fi
    - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - npm install --registry https://registry.npm.taobao.org

create_npmrc:
  stage: build
  script:
    - |
      npm run build

publish_package:
  stage: deploy
  script:
    - |
      mv ./dist public
  artifacts:
    paths:
      - public
